export default class ConfigVO {
  constructor () {
    this.jdbcEntityFilePath = null
    this.hibernateEntityFilePath = null
    this.exceptionFilePath = null
    this.persistentInterfaceFilePath = null
    this.jdbcPersistentImplFilePath = null
    this.serviceInterfaceFilePath = null
    this.serviceImplFilePath = null
    this.controllerFilePath = null
    this.angularModuleFilePath = null
    this.angularRoutingFilePath = null
    this.angularEntityFilePath = null
    this.angularServiceFilePath = null
    this.angularListComponentFilePath = null
    this.angularListHtmlFilePath = null
    this.angularListCssFilePath = null
    this.angularEditComponentFilePath = null
    this.angularEditHtmlFilePath = null
    this.angularEditCssFilePath = null
    this.angularDetailComponentFilePath = null
    this.angularDetailHtmlFilePath = null
    this.angularDetailCssFilePath = null
    this.queryFilePath = null
    this.angularQueryFilePath = null
    this.projectPath = null
    this.voFilePath = null
    this.vueEntityFilePath = null
    this.vueQueryFilePath = null
    this.vueVoFilePath = null
    this.vueServiceFilePath = null
    this.vueStoreFilePath = null
    this.vueListFilePath = null
    this.vueListCssFilePath = null
    this.vueEditFilePath = null
    this.vueEditCssFilePath = null
    this.vueDetailFilePath = null
    this.vueDetailCssFilePath = null
    this.jpaPersistentInterfaceFilePath = null
    this.vueViewFilePath = null
    this.vueViewCssFilePath = null
    this.dtId = null
  }
}
